package com.rebs.db.domain;

import java.util.ArrayList;
import java.util.Date;

import lombok.Data;

@Data
public class SystemUserView {

    private String userId;
    
    private String password;
    
    private Integer roleId;
    
    private String postName;
    private String fullName;
    private String shortName;
    private String orgIdPath;
    
    private ArrayList<String> orgNames;
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Integer employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.ORG_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.POST_NO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String postNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.SEX
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.BIRTHDAY
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.NATIVE_PLACE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.FOLK
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String folk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.WEDDING
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short wedding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.BEGIN_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.WORK_PHONE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String workPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.HOME_PHONE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String homePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.MOBILE_PHONE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.EMAIL
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.ADDRESS
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.POST_CODE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.ISONPOST
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short isonpost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.MEMO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.IS_GROUP_LEADER
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short isGroupLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.TECHNICIAN_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short technicianTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.WORK_NO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String workNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.PINYIN_CODE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String pinyinCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.LOGIN_COUNT
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.LOGIN_TIME
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Integer loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.IDENTITY_CARDNO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String identityCardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.POLITICAL_STATUS_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short politicalStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.JOIN_RAIL_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Date joinRailDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.EDUCATION_LEVEL_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short educationLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short employeeTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.SECOND_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Integer secondPostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.THIRD_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Integer thirdPostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short technicalTitleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short workgroupleaderTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_ORDER_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Date workgroupleaderOrderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.EDUCATION_EMPLOYEE_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short educationEmployeeTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.COMMITTEE_HEAD_SHIP_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short committeeHeadShipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.ISREGISTERED
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short isregistered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TRANSPORT_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short employeeTransportTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.AWARD_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Date awardDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.COULD_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String couldPostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Date technicalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Date technicalTitleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.POST_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Date postDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.GRADUATE_UNIVERSITY
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String graduateUniversity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.GRADUATE_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Date graduateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.STUDY_MAJOR
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String studyMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.UNIVERSITY_TYPE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Short universityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_CODE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private String technicalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.SAFE_LEVEL_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Integer safeLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAILEXAMBAO.EMPLOYEE.NOW_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    private Integer nowPostId;

    private String fileUrl;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.EMPLOYEE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_ID
     *
     * @param employeeId the value for RAILEXAMBAO.EMPLOYEE.EMPLOYEE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.ORG_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.ORG_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.ORG_ID
     *
     * @param orgId the value for RAILEXAMBAO.EMPLOYEE.ORG_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.POST_NO
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.POST_NO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getPostNo() {
        return postNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.POST_NO
     *
     * @param postNo the value for RAILEXAMBAO.EMPLOYEE.POST_NO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setPostNo(String postNo) {
        this.postNo = postNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_NAME
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_NAME
     *
     * @param employeeName the value for RAILEXAMBAO.EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.POST_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.POST_ID
     *
     * @param postId the value for RAILEXAMBAO.EMPLOYEE.POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.SEX
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.SEX
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.SEX
     *
     * @param sex the value for RAILEXAMBAO.EMPLOYEE.SEX
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.BIRTHDAY
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.BIRTHDAY
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.BIRTHDAY
     *
     * @param birthday the value for RAILEXAMBAO.EMPLOYEE.BIRTHDAY
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.NATIVE_PLACE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.NATIVE_PLACE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.NATIVE_PLACE
     *
     * @param nativePlace the value for RAILEXAMBAO.EMPLOYEE.NATIVE_PLACE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.FOLK
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.FOLK
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getFolk() {
        return folk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.FOLK
     *
     * @param folk the value for RAILEXAMBAO.EMPLOYEE.FOLK
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setFolk(String folk) {
        this.folk = folk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.WEDDING
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.WEDDING
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getWedding() {
        return wedding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.WEDDING
     *
     * @param wedding the value for RAILEXAMBAO.EMPLOYEE.WEDDING
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setWedding(Short wedding) {
        this.wedding = wedding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.BEGIN_DATE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.BEGIN_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.BEGIN_DATE
     *
     * @param beginDate the value for RAILEXAMBAO.EMPLOYEE.BEGIN_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.WORK_PHONE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.WORK_PHONE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getWorkPhone() {
        return workPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.WORK_PHONE
     *
     * @param workPhone the value for RAILEXAMBAO.EMPLOYEE.WORK_PHONE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setWorkPhone(String workPhone) {
        this.workPhone = workPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.HOME_PHONE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.HOME_PHONE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.HOME_PHONE
     *
     * @param homePhone the value for RAILEXAMBAO.EMPLOYEE.HOME_PHONE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.MOBILE_PHONE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.MOBILE_PHONE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.MOBILE_PHONE
     *
     * @param mobilePhone the value for RAILEXAMBAO.EMPLOYEE.MOBILE_PHONE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.EMAIL
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.EMAIL
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.EMAIL
     *
     * @param email the value for RAILEXAMBAO.EMPLOYEE.EMAIL
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.ADDRESS
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.ADDRESS
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.ADDRESS
     *
     * @param address the value for RAILEXAMBAO.EMPLOYEE.ADDRESS
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.POST_CODE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.POST_CODE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.POST_CODE
     *
     * @param postCode the value for RAILEXAMBAO.EMPLOYEE.POST_CODE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.ISONPOST
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.ISONPOST
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getIsonpost() {
        return isonpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.ISONPOST
     *
     * @param isonpost the value for RAILEXAMBAO.EMPLOYEE.ISONPOST
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setIsonpost(Short isonpost) {
        this.isonpost = isonpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.MEMO
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.MEMO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.MEMO
     *
     * @param memo the value for RAILEXAMBAO.EMPLOYEE.MEMO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.IS_GROUP_LEADER
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.IS_GROUP_LEADER
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getIsGroupLeader() {
        return isGroupLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.IS_GROUP_LEADER
     *
     * @param isGroupLeader the value for RAILEXAMBAO.EMPLOYEE.IS_GROUP_LEADER
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setIsGroupLeader(Short isGroupLeader) {
        this.isGroupLeader = isGroupLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICIAN_TYPE_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.TECHNICIAN_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getTechnicianTypeId() {
        return technicianTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICIAN_TYPE_ID
     *
     * @param technicianTypeId the value for RAILEXAMBAO.EMPLOYEE.TECHNICIAN_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setTechnicianTypeId(Short technicianTypeId) {
        this.technicianTypeId = technicianTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.WORK_NO
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.WORK_NO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getWorkNo() {
        return workNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.WORK_NO
     *
     * @param workNo the value for RAILEXAMBAO.EMPLOYEE.WORK_NO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setWorkNo(String workNo) {
        this.workNo = workNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.PINYIN_CODE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.PINYIN_CODE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getPinyinCode() {
        return pinyinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.PINYIN_CODE
     *
     * @param pinyinCode the value for RAILEXAMBAO.EMPLOYEE.PINYIN_CODE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setPinyinCode(String pinyinCode) {
        this.pinyinCode = pinyinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.LOGIN_COUNT
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.LOGIN_COUNT
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.LOGIN_COUNT
     *
     * @param loginCount the value for RAILEXAMBAO.EMPLOYEE.LOGIN_COUNT
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.LOGIN_TIME
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.LOGIN_TIME
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Integer getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.LOGIN_TIME
     *
     * @param loginTime the value for RAILEXAMBAO.EMPLOYEE.LOGIN_TIME
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setLoginTime(Integer loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.IDENTITY_CARDNO
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.IDENTITY_CARDNO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getIdentityCardno() {
        return identityCardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.IDENTITY_CARDNO
     *
     * @param identityCardno the value for RAILEXAMBAO.EMPLOYEE.IDENTITY_CARDNO
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setIdentityCardno(String identityCardno) {
        this.identityCardno = identityCardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.POLITICAL_STATUS_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.POLITICAL_STATUS_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getPoliticalStatusId() {
        return politicalStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.POLITICAL_STATUS_ID
     *
     * @param politicalStatusId the value for RAILEXAMBAO.EMPLOYEE.POLITICAL_STATUS_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setPoliticalStatusId(Short politicalStatusId) {
        this.politicalStatusId = politicalStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.JOIN_RAIL_DATE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.JOIN_RAIL_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Date getJoinRailDate() {
        return joinRailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.JOIN_RAIL_DATE
     *
     * @param joinRailDate the value for RAILEXAMBAO.EMPLOYEE.JOIN_RAIL_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setJoinRailDate(Date joinRailDate) {
        this.joinRailDate = joinRailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.EDUCATION_LEVEL_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.EDUCATION_LEVEL_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getEducationLevelId() {
        return educationLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.EDUCATION_LEVEL_ID
     *
     * @param educationLevelId the value for RAILEXAMBAO.EMPLOYEE.EDUCATION_LEVEL_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setEducationLevelId(Short educationLevelId) {
        this.educationLevelId = educationLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TYPE_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getEmployeeTypeId() {
        return employeeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TYPE_ID
     *
     * @param employeeTypeId the value for RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setEmployeeTypeId(Short employeeTypeId) {
        this.employeeTypeId = employeeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.SECOND_POST_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.SECOND_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Integer getSecondPostId() {
        return secondPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.SECOND_POST_ID
     *
     * @param secondPostId the value for RAILEXAMBAO.EMPLOYEE.SECOND_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setSecondPostId(Integer secondPostId) {
        this.secondPostId = secondPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.THIRD_POST_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.THIRD_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Integer getThirdPostId() {
        return thirdPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.THIRD_POST_ID
     *
     * @param thirdPostId the value for RAILEXAMBAO.EMPLOYEE.THIRD_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setThirdPostId(Integer thirdPostId) {
        this.thirdPostId = thirdPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getTechnicalTitleId() {
        return technicalTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_ID
     *
     * @param technicalTitleId the value for RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setTechnicalTitleId(Short technicalTitleId) {
        this.technicalTitleId = technicalTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_TYPE_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getWorkgroupleaderTypeId() {
        return workgroupleaderTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_TYPE_ID
     *
     * @param workgroupleaderTypeId the value for RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setWorkgroupleaderTypeId(Short workgroupleaderTypeId) {
        this.workgroupleaderTypeId = workgroupleaderTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_ORDER_DATE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_ORDER_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Date getWorkgroupleaderOrderDate() {
        return workgroupleaderOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_ORDER_DATE
     *
     * @param workgroupleaderOrderDate the value for RAILEXAMBAO.EMPLOYEE.WORKGROUPLEADER_ORDER_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setWorkgroupleaderOrderDate(Date workgroupleaderOrderDate) {
        this.workgroupleaderOrderDate = workgroupleaderOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.EDUCATION_EMPLOYEE_TYPE_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.EDUCATION_EMPLOYEE_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getEducationEmployeeTypeId() {
        return educationEmployeeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.EDUCATION_EMPLOYEE_TYPE_ID
     *
     * @param educationEmployeeTypeId the value for RAILEXAMBAO.EMPLOYEE.EDUCATION_EMPLOYEE_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setEducationEmployeeTypeId(Short educationEmployeeTypeId) {
        this.educationEmployeeTypeId = educationEmployeeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.COMMITTEE_HEAD_SHIP_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.COMMITTEE_HEAD_SHIP_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getCommitteeHeadShipId() {
        return committeeHeadShipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.COMMITTEE_HEAD_SHIP_ID
     *
     * @param committeeHeadShipId the value for RAILEXAMBAO.EMPLOYEE.COMMITTEE_HEAD_SHIP_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setCommitteeHeadShipId(Short committeeHeadShipId) {
        this.committeeHeadShipId = committeeHeadShipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.ISREGISTERED
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.ISREGISTERED
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getIsregistered() {
        return isregistered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.ISREGISTERED
     *
     * @param isregistered the value for RAILEXAMBAO.EMPLOYEE.ISREGISTERED
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setIsregistered(Short isregistered) {
        this.isregistered = isregistered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TRANSPORT_TYPE_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TRANSPORT_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getEmployeeTransportTypeId() {
        return employeeTransportTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TRANSPORT_TYPE_ID
     *
     * @param employeeTransportTypeId the value for RAILEXAMBAO.EMPLOYEE.EMPLOYEE_TRANSPORT_TYPE_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setEmployeeTransportTypeId(Short employeeTransportTypeId) {
        this.employeeTransportTypeId = employeeTransportTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.AWARD_DATE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.AWARD_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Date getAwardDate() {
        return awardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.AWARD_DATE
     *
     * @param awardDate the value for RAILEXAMBAO.EMPLOYEE.AWARD_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setAwardDate(Date awardDate) {
        this.awardDate = awardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.COULD_POST_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.COULD_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getCouldPostId() {
        return couldPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.COULD_POST_ID
     *
     * @param couldPostId the value for RAILEXAMBAO.EMPLOYEE.COULD_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setCouldPostId(String couldPostId) {
        this.couldPostId = couldPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_DATE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.TECHNICAL_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Date getTechnicalDate() {
        return technicalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_DATE
     *
     * @param technicalDate the value for RAILEXAMBAO.EMPLOYEE.TECHNICAL_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setTechnicalDate(Date technicalDate) {
        this.technicalDate = technicalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_DATE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Date getTechnicalTitleDate() {
        return technicalTitleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_DATE
     *
     * @param technicalTitleDate the value for RAILEXAMBAO.EMPLOYEE.TECHNICAL_TITLE_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setTechnicalTitleDate(Date technicalTitleDate) {
        this.technicalTitleDate = technicalTitleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.POST_DATE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.POST_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Date getPostDate() {
        return postDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.POST_DATE
     *
     * @param postDate the value for RAILEXAMBAO.EMPLOYEE.POST_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.GRADUATE_UNIVERSITY
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.GRADUATE_UNIVERSITY
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getGraduateUniversity() {
        return graduateUniversity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.GRADUATE_UNIVERSITY
     *
     * @param graduateUniversity the value for RAILEXAMBAO.EMPLOYEE.GRADUATE_UNIVERSITY
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setGraduateUniversity(String graduateUniversity) {
        this.graduateUniversity = graduateUniversity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.GRADUATE_DATE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.GRADUATE_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Date getGraduateDate() {
        return graduateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.GRADUATE_DATE
     *
     * @param graduateDate the value for RAILEXAMBAO.EMPLOYEE.GRADUATE_DATE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setGraduateDate(Date graduateDate) {
        this.graduateDate = graduateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.STUDY_MAJOR
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.STUDY_MAJOR
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getStudyMajor() {
        return studyMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.STUDY_MAJOR
     *
     * @param studyMajor the value for RAILEXAMBAO.EMPLOYEE.STUDY_MAJOR
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setStudyMajor(String studyMajor) {
        this.studyMajor = studyMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.UNIVERSITY_TYPE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.UNIVERSITY_TYPE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Short getUniversityType() {
        return universityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.UNIVERSITY_TYPE
     *
     * @param universityType the value for RAILEXAMBAO.EMPLOYEE.UNIVERSITY_TYPE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setUniversityType(Short universityType) {
        this.universityType = universityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_CODE
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.TECHNICAL_CODE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public String getTechnicalCode() {
        return technicalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.TECHNICAL_CODE
     *
     * @param technicalCode the value for RAILEXAMBAO.EMPLOYEE.TECHNICAL_CODE
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setTechnicalCode(String technicalCode) {
        this.technicalCode = technicalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.SAFE_LEVEL_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.SAFE_LEVEL_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Integer getSafeLevelId() {
        return safeLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.SAFE_LEVEL_ID
     *
     * @param safeLevelId the value for RAILEXAMBAO.EMPLOYEE.SAFE_LEVEL_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setSafeLevelId(Integer safeLevelId) {
        this.safeLevelId = safeLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAILEXAMBAO.EMPLOYEE.NOW_POST_ID
     *
     * @return the value of RAILEXAMBAO.EMPLOYEE.NOW_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public Integer getNowPostId() {
        return nowPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAILEXAMBAO.EMPLOYEE.NOW_POST_ID
     *
     * @param nowPostId the value for RAILEXAMBAO.EMPLOYEE.NOW_POST_ID
     *
     * @mbggenerated Sat Sep 29 13:42:39 CST 2018
     */
    public void setNowPostId(Integer nowPostId) {
        this.nowPostId = nowPostId;
    }
}
