package com.rebs.db.dao;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import com.rebs.db.domain.CollectionItem;
import com.rebs.db.domain.CollectionOfBook;
import com.rebs.db.domain.Item;

public interface CollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RANDOM_EXAM_EMPLOYEE_COLLECT
     *
     * @mbggenerated Fri Sep 28 16:36:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RANDOM_EXAM_EMPLOYEE_COLLECT
     *
     * @mbggenerated Fri Sep 28 16:36:33 CST 2018
     */
    int insert(CollectionItem collection);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RANDOM_EXAM_EMPLOYEE_COLLECT
     *
     * @mbggenerated Fri Sep 28 16:36:33 CST 2018
     */
    int insertSelective(CollectionItem collection);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RANDOM_EXAM_EMPLOYEE_COLLECT
     *
     * @mbggenerated Fri Sep 28 16:36:33 CST 2018
     */
    CollectionItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RANDOM_EXAM_EMPLOYEE_COLLECT
     *
     * @mbggenerated Fri Sep 28 16:36:33 CST 2018
     */
    int updateByPrimaryKeySelective(CollectionItem collection);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RANDOM_EXAM_EMPLOYEE_COLLECT
     *
     * @mbggenerated Fri Sep 28 16:36:33 CST 2018
     */
    int updateByPrimaryKey(CollectionItem collection);
    
    
    List<CollectionItem> selectCollection(CollectionItem collection);

	int deleteByCollection(CollectionItem collection);
	
	/**
	 * 收藏的题数通过书名分类
	 * @param collection
	 * @return
	 */
	List<CollectionOfBook> selectCollectionCountOfBook(CollectionItem collection);
	
	/**
	 * 根据employeeId，typeId，bookId 查询所有收藏题目收藏题目详情
	 * @param map
	 * @return
	 */
	ArrayList<Item> selectCollectionItemDetail(Map<Object, Object> map);
}