package com.rebs.db.dao;

import java.util.List;

import com.rebs.db.domain.Employee;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbggenerated Fri Sep 28 17:43:05 CST 2018
     */
    int deleteByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbggenerated Fri Sep 28 17:43:05 CST 2018
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbggenerated Fri Sep 28 17:43:05 CST 2018
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbggenerated Fri Sep 28 17:43:05 CST 2018
     */
    Employee selectByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbggenerated Fri Sep 28 17:43:05 CST 2018
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbggenerated Fri Sep 28 17:43:05 CST 2018
     */
    int updateByPrimaryKey(Employee record);
    
    
    List<Employee> getEmployeeByWorkNo(String workNo);
    
    
    /**
     * 新增员工的openId
     * @param record
     * @return
     */
    int insertWxEmployee(Employee record);
    
    /**
     * 查询员工的openId是否存在
     * @param employeeId
     * @return
     */
    Employee selectWxEmployeeByEmployeeId(Integer employeeId);
    
    /**
     * 更新员工的openId
     * @param record
     * @return
     */
    int updateWxEmployee(Employee record);
    
    
}