package com.rebs.db.dao;

import java.util.List;

import com.rebs.db.domain.SystemUser;
import com.rebs.db.domain.SystemUserView;

public interface SystemUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER
     *
     * @mbggenerated Fri Sep 28 17:40:33 CST 2018
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER
     *
     * @mbggenerated Fri Sep 28 17:40:33 CST 2018
     */
    int insert(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER
     *
     * @mbggenerated Fri Sep 28 17:40:33 CST 2018
     */
    int insertSelective(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER
     *
     * @mbggenerated Fri Sep 28 17:40:33 CST 2018
     */
    SystemUser selectByPrimaryKey(String userId);
    
    
    List<SystemUserView> selectByMobilePhone(String mobilePhone);
    
    List<SystemUserView> selectByWorkNo(String workNo);
    
    
    List<SystemUserView> selectByOpenId(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER
     *
     * @mbggenerated Fri Sep 28 17:40:33 CST 2018
     */
    int updateByPrimaryKeySelective(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER
     *
     * @mbggenerated Fri Sep 28 17:40:33 CST 2018
     */
    int updateByPrimaryKey(SystemUser record);
}